version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: my_app
      DB_USERNAME: root
      DB_PASSWORD: password
  db:
    image: mysql:5.7
    container_name: my-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: my_app
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
  web:
    image: php:7.4-apache
    container_name: my-apache
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db-data:
